/**
 * generated by Xtext 2.14.0
 */
package org.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.example.ui.AbstractDomainmodelUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DomainmodelUiModule extends AbstractDomainmodelUiModule {
  public DomainmodelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
