/**
 * generated by Xtext 2.14.0
 */
package org.example.domainmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruction Wait</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.InstructionWait#getTps <em>Tps</em>}</li>
 * </ul>
 *
 * @see org.example.domainmodel.DomainmodelPackage#getInstructionWait()
 * @model
 * @generated
 */
public interface InstructionWait extends Instruction
{
  /**
   * Returns the value of the '<em><b>Tps</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tps</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tps</em>' attribute.
   * @see #setTps(int)
   * @see org.example.domainmodel.DomainmodelPackage#getInstructionWait_Tps()
   * @model
   * @generated
   */
  int getTps();

  /**
   * Sets the value of the '{@link org.example.domainmodel.InstructionWait#getTps <em>Tps</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tps</em>' attribute.
   * @see #getTps()
   * @generated
   */
  void setTps(int value);

} // InstructionWait
