/**
 * generated by Xtext 2.14.0
 */
package org.example.domainmodel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Start Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.StartPoint#getInstructions <em>Instructions</em>}</li>
 * </ul>
 *
 * @see org.example.domainmodel.DomainmodelPackage#getStartPoint()
 * @model
 * @generated
 */
public interface StartPoint extends EObject
{
  /**
   * Returns the value of the '<em><b>Instructions</b></em>' containment reference list.
   * The list contents are of type {@link org.example.domainmodel.Instruction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Instructions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instructions</em>' containment reference list.
   * @see org.example.domainmodel.DomainmodelPackage#getStartPoint_Instructions()
   * @model containment="true"
   * @generated
   */
  EList<Instruction> getInstructions();

} // StartPoint
