/**
 * generated by Xtext 2.14.0
 */
package org.example.ide;

import org.example.ide.AbstractDomainmodelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
