/**
 * generated by Xtext 2.14.0
 */
package org.example;

import org.example.AbstractDomainmodelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainmodelRuntimeModule extends AbstractDomainmodelRuntimeModule {
}
