/**
 * generated by Xtext 2.14.0
 */
package org.example.domainmodel.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.example.domainmodel.DomainmodelPackage;
import org.example.domainmodel.InstructionMove;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Instruction Move</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.domainmodel.impl.InstructionMoveImpl#getFrom <em>From</em>}</li>
 *   <li>{@link org.example.domainmodel.impl.InstructionMoveImpl#getTo <em>To</em>}</li>
 *   <li>{@link org.example.domainmodel.impl.InstructionMoveImpl#getQty <em>Qty</em>}</li>
 *   <li>{@link org.example.domainmodel.impl.InstructionMoveImpl#getFilter <em>Filter</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InstructionMoveImpl extends InstructionImpl implements InstructionMove
{
  /**
   * The default value of the '{@link #getFrom() <em>From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrom()
   * @generated
   * @ordered
   */
  protected static final int FROM_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getFrom() <em>From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrom()
   * @generated
   * @ordered
   */
  protected int from = FROM_EDEFAULT;

  /**
   * The default value of the '{@link #getTo() <em>To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTo()
   * @generated
   * @ordered
   */
  protected static final int TO_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTo() <em>To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTo()
   * @generated
   * @ordered
   */
  protected int to = TO_EDEFAULT;

  /**
   * The default value of the '{@link #getQty() <em>Qty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQty()
   * @generated
   * @ordered
   */
  protected static final int QTY_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getQty() <em>Qty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQty()
   * @generated
   * @ordered
   */
  protected int qty = QTY_EDEFAULT;

  /**
   * The default value of the '{@link #getFilter() <em>Filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFilter()
   * @generated
   * @ordered
   */
  protected static final int FILTER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getFilter() <em>Filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFilter()
   * @generated
   * @ordered
   */
  protected int filter = FILTER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InstructionMoveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainmodelPackage.Literals.INSTRUCTION_MOVE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getFrom()
  {
    return from;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFrom(int newFrom)
  {
    int oldFrom = from;
    from = newFrom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.INSTRUCTION_MOVE__FROM, oldFrom, from));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTo()
  {
    return to;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTo(int newTo)
  {
    int oldTo = to;
    to = newTo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.INSTRUCTION_MOVE__TO, oldTo, to));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getQty()
  {
    return qty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setQty(int newQty)
  {
    int oldQty = qty;
    qty = newQty;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.INSTRUCTION_MOVE__QTY, oldQty, qty));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getFilter()
  {
    return filter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFilter(int newFilter)
  {
    int oldFilter = filter;
    filter = newFilter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.INSTRUCTION_MOVE__FILTER, oldFilter, filter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DomainmodelPackage.INSTRUCTION_MOVE__FROM:
        return getFrom();
      case DomainmodelPackage.INSTRUCTION_MOVE__TO:
        return getTo();
      case DomainmodelPackage.INSTRUCTION_MOVE__QTY:
        return getQty();
      case DomainmodelPackage.INSTRUCTION_MOVE__FILTER:
        return getFilter();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DomainmodelPackage.INSTRUCTION_MOVE__FROM:
        setFrom((Integer)newValue);
        return;
      case DomainmodelPackage.INSTRUCTION_MOVE__TO:
        setTo((Integer)newValue);
        return;
      case DomainmodelPackage.INSTRUCTION_MOVE__QTY:
        setQty((Integer)newValue);
        return;
      case DomainmodelPackage.INSTRUCTION_MOVE__FILTER:
        setFilter((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DomainmodelPackage.INSTRUCTION_MOVE__FROM:
        setFrom(FROM_EDEFAULT);
        return;
      case DomainmodelPackage.INSTRUCTION_MOVE__TO:
        setTo(TO_EDEFAULT);
        return;
      case DomainmodelPackage.INSTRUCTION_MOVE__QTY:
        setQty(QTY_EDEFAULT);
        return;
      case DomainmodelPackage.INSTRUCTION_MOVE__FILTER:
        setFilter(FILTER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DomainmodelPackage.INSTRUCTION_MOVE__FROM:
        return from != FROM_EDEFAULT;
      case DomainmodelPackage.INSTRUCTION_MOVE__TO:
        return to != TO_EDEFAULT;
      case DomainmodelPackage.INSTRUCTION_MOVE__QTY:
        return qty != QTY_EDEFAULT;
      case DomainmodelPackage.INSTRUCTION_MOVE__FILTER:
        return filter != FILTER_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (from: ");
    result.append(from);
    result.append(", to: ");
    result.append(to);
    result.append(", qty: ");
    result.append(qty);
    result.append(", filter: ");
    result.append(filter);
    result.append(')');
    return result.toString();
  }

} //InstructionMoveImpl
