/*
 * generated by Xtext 2.14.0
 */
package org.example.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.example.ide.contentassist.antlr.internal.InternalDomainmodelParser;
import org.example.services.DomainmodelGrammarAccess;

public class DomainmodelParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DomainmodelGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DomainmodelGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
			builder.put(grammarAccess.getStartPointAccess().getGroup(), "rule__StartPoint__Group__0");
			builder.put(grammarAccess.getInstructionMoveAccess().getGroup(), "rule__InstructionMove__Group__0");
			builder.put(grammarAccess.getInstructionMoveAccess().getGroup_7(), "rule__InstructionMove__Group_7__0");
			builder.put(grammarAccess.getInstructionWaitAccess().getGroup(), "rule__InstructionWait__Group__0");
			builder.put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
			builder.put(grammarAccess.getEntityAccess().getGroup_2(), "rule__Entity__Group_2__0");
			builder.put(grammarAccess.getStartPointAccess().getInstructionsAssignment_3(), "rule__StartPoint__InstructionsAssignment_3");
			builder.put(grammarAccess.getInstructionMoveAccess().getFromAssignment_2(), "rule__InstructionMove__FromAssignment_2");
			builder.put(grammarAccess.getInstructionMoveAccess().getToAssignment_4(), "rule__InstructionMove__ToAssignment_4");
			builder.put(grammarAccess.getInstructionMoveAccess().getQtyAssignment_6(), "rule__InstructionMove__QtyAssignment_6");
			builder.put(grammarAccess.getInstructionMoveAccess().getFilterAssignment_7_1(), "rule__InstructionMove__FilterAssignment_7_1");
			builder.put(grammarAccess.getInstructionWaitAccess().getTpsAssignment_1(), "rule__InstructionWait__TpsAssignment_1");
			builder.put(grammarAccess.getDomainmodelAccess().getElementsAssignment(), "rule__Domainmodel__ElementsAssignment");
			builder.put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
			builder.put(grammarAccess.getEntityAccess().getSuperTypeAssignment_2_1(), "rule__Entity__SuperTypeAssignment_2_1");
			builder.put(grammarAccess.getEntityAccess().getStartPointAssignment_4(), "rule__Entity__StartPointAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DomainmodelGrammarAccess grammarAccess;

	@Override
	protected InternalDomainmodelParser createParser() {
		InternalDomainmodelParser result = new InternalDomainmodelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DomainmodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DomainmodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
