/**
 * generated by Xtext 2.14.0
 */
package org.example.ui.contentassist;

import org.example.ui.contentassist.AbstractDomainmodelProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DomainmodelProposalProvider extends AbstractDomainmodelProposalProvider {
}
